import Navigation from "@/react-app/components/Navigation";
import Footer from "@/react-app/components/Footer";
import GlassCard from "@/react-app/components/GlassCard";
import { AlertTriangle, ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router";
import Button from "@/react-app/components/Button";

export default function Disclaimer() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-white text-gray-900">
      <Navigation />

      <main className="relative z-10">
        {/* Header */}
        <section className="px-6 pt-8 pb-6 border-b border-gray-100">
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center gap-4 mb-2">
              <Button 
                variant="ghost" 
                onClick={() => navigate("/")}
                className="p-2 hover:bg-gray-100 rounded-full"
              >
                <ArrowLeft className="w-5 h-5 text-gray-600" />
              </Button>
              
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-gradient-to-br from-amber-500 to-orange-500 rounded-2xl flex items-center justify-center shadow-lg">
                  <AlertTriangle className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h1 className="text-2xl font-semibold text-gray-900">Legal Disclaimer</h1>
                  <p className="text-gray-600 font-light">Important limitations and disclosures</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Disclaimer Content */}
        <section className="px-6 py-16">
          <div className="max-w-4xl mx-auto">
            <GlassCard 
              className="p-8 md:p-12 backdrop-blur-3xl border-gray-200/30 shadow-xl"
              opacity={0.05}
              blur="xl"
            >
              <div className="prose prose-lg max-w-none space-y-8">
                {/* Main Disclaimer */}
                <div className="p-8 bg-gradient-to-r from-red-50 to-orange-50 border-2 border-red-200 rounded-2xl mb-8">
                  <h2 className="text-2xl font-bold text-red-800 mb-4 flex items-center gap-3">
                    <AlertTriangle className="w-6 h-6" />
                    THIS IS NOT LEGAL ADVICE
                  </h2>
                  <p className="text-red-700 font-light leading-relaxed text-lg">
                    <strong>OutLaw is an educational study tool designed exclusively for law school exam preparation. 
                    The AI-generated content, predictions, and study materials provided by this service are for 
                    educational purposes only and should NEVER be relied upon as legal advice or professional counsel.</strong>
                  </p>
                </div>

                <section>
                  <h2 className="text-xl font-semibold text-gray-900 mb-4">Educational Purpose Only</h2>
                  <p className="text-gray-700 font-light leading-relaxed mb-4">
                    OutLaw is designed specifically to help law students:
                  </p>
                  <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 mb-4 font-light">
                    <li>Prepare for law school examinations</li>
                    <li>Study course materials more effectively</li>
                    <li>Practice legal analysis and writing</li>
                    <li>Understand professorial teaching styles and exam patterns</li>
                  </ul>
                  <p className="text-gray-700 font-light leading-relaxed">
                    The service is NOT intended for, and should NEVER be used for, actual legal matters, 
                    client representation, or real-world legal decision making.
                  </p>
                </section>

                <section>
                  <h2 className="text-xl font-semibold text-gray-900 mb-4">Accuracy Limitations</h2>
                  <div className="p-6 bg-gradient-to-r from-yellow-50 to-amber-50 border border-yellow-200 rounded-2xl mb-4">
                    <p className="text-yellow-800 font-semibold">
                      We cannot guarantee the accuracy of AI-generated content or exam predictions.
                    </p>
                  </div>
                  <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 font-light">
                    <li>AI predictions are estimates based on available data and patterns</li>
                    <li>Actual exams may differ significantly from AI predictions</li>
                    <li>Legal analysis generated by AI may contain errors or omissions</li>
                    <li>Users must verify all information with authoritative legal sources</li>
                    <li>Professor personalities and teaching styles may not be perfectly replicated</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-xl font-semibold text-gray-900 mb-4">Professional Legal Consultation</h2>
                  <p className="text-gray-700 font-light leading-relaxed mb-4">
                    For any actual legal matters, concerns, or questions requiring professional legal judgment, 
                    you must consult with:
                  </p>
                  <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 font-light">
                    <li>Licensed attorneys in the relevant jurisdiction</li>
                    <li>Law school professors and clinical supervisors</li>
                    <li>Legal aid organizations</li>
                    <li>Bar association referral services</li>
                    <li>Other qualified legal professionals</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-xl font-semibold text-gray-900 mb-4">Academic Integrity</h2>
                  <p className="text-gray-700 font-light leading-relaxed mb-4">
                    Users are responsible for ensuring their use of OutLaw complies with their law school's 
                    academic integrity policies. This includes:
                  </p>
                  <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 font-light">
                    <li>Understanding what constitutes authorized assistance on exams and assignments</li>
                    <li>Properly attributing any ideas or analysis derived from AI-generated content</li>
                    <li>Not using the service during closed-book exams unless explicitly permitted</li>
                    <li>Following all school-specific rules regarding AI assistance tools</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-xl font-semibold text-gray-900 mb-4">Limitation of Liability</h2>
                  <div className="p-6 bg-gradient-to-r from-gray-50 to-slate-50 border border-gray-200 rounded-2xl mb-4">
                    <p className="text-gray-800 font-semibold">
                      OutLaw and its operators are NOT liable for any consequences arising from use of this service.
                    </p>
                  </div>
                  <p className="text-gray-700 font-light leading-relaxed mb-4">This includes but is not limited to:</p>
                  <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 font-light">
                    <li>Poor exam performance or academic outcomes</li>
                    <li>Academic integrity violations</li>
                    <li>Reliance on inaccurate AI-generated content</li>
                    <li>Professional or career consequences</li>
                    <li>Any damages resulting from service use or unavailability</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-xl font-semibold text-gray-900 mb-4">AI Technology Limitations</h2>
                  <p className="text-gray-700 font-light leading-relaxed mb-4">
                    Users should understand that AI technology:
                  </p>
                  <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 font-light">
                    <li>May generate plausible but incorrect information</li>
                    <li>Cannot replace human judgment or expertise</li>
                    <li>May have biases present in training data</li>
                    <li>Cannot account for recent legal developments</li>
                    <li>May misinterpret context or nuance</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-xl font-semibold text-gray-900 mb-4">User Responsibility</h2>
                  <p className="text-gray-700 font-light leading-relaxed mb-4">By using OutLaw, you acknowledge that:</p>
                  <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 font-light">
                    <li>You understand this disclaimer and its implications</li>
                    <li>You will not rely on AI-generated content for legal advice</li>
                    <li>You will verify all information with authoritative sources</li>
                    <li>You accept full responsibility for your use of the service</li>
                    <li>You will comply with all applicable academic and professional standards</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-xl font-semibold text-gray-900 mb-4">Geographic Limitations</h2>
                  <p className="text-gray-700 font-light leading-relaxed">
                    OutLaw's content is primarily based on U.S. legal education standards and may not be 
                    applicable to legal systems in other jurisdictions. International users should be 
                    particularly cautious about applying any content to their local legal context.
                  </p>
                </section>

                <section>
                  <h2 className="text-xl font-semibold text-gray-900 mb-4">Updates and Changes</h2>
                  <p className="text-gray-700 font-light leading-relaxed">
                    This disclaimer may be updated periodically. Continued use of the service after changes 
                    constitutes acceptance of the updated disclaimer. Users are encouraged to review this 
                    page regularly.
                  </p>
                </section>

                {/* Made with Heart Message */}
                <div className="p-8 bg-gradient-to-r from-purple-50 to-indigo-50 border border-purple-200 rounded-2xl mb-8 text-center">
                  <div className="flex items-center justify-center gap-2 text-purple-800 font-semibold text-lg mb-2">
                    <span>Made with</span>
                    <div className="w-5 h-5 text-red-500">❤️</div>
                    <span>by law students, for law students</span>
                  </div>
                  <p className="text-purple-700 font-light">
                    We understand the struggle because we've lived it. OutLaw was built by law students who know firsthand how challenging exam preparation can be.
                  </p>
                </div>

                <div className="p-8 bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200 rounded-2xl">
                  <p className="text-blue-800 font-semibold text-center text-lg">
                    Questions about this disclaimer? Contact us for clarification. <br />
                    Remember: When in doubt, consult a licensed attorney for legal matters.
                  </p>
                </div>
              </div>
            </GlassCard>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
